### ISSUE TITLE
Expose AppVeyor configuration to GitHub (add appveyor.yml)

### ISSUE THREAD

**Issue by EwoutH** [hexchat/hexchat#2303]
Right now the AppVeyor configuration is not visible from GitHub. It would be nice the configuration could be adjusted from GitHub by publishing the `appveyor.yml` file. If AppVeyor was configured from the UI the appveyor.yml can be generated from the _Export YAML_ tab in the AppVeyor menu.

I would like to add a deploy function (so that .exe artifacts get uploaded to GitHub on release) and Arm64 (aarch64) builds for example.

**Comment by TingPing** [comment]
Here it is (sans deploy):
```yaml

version: 1.0.{build}
image: Visual Studio 2015
shallow_clone: true
environment:
  matrix:
  - platform: x64
    arch: x64
  - platform: win32
    arch: x86
before_build:
- cmd: "set PATH=\"C:\\Program Files\\7-Zip\";%PATH%\n\nappveyor DownloadFile http://www.jrsoftware.org/download.php/is-unicode.exe\nis-unicode.exe /VERYSILENT\n\nappveyor DownloadFile https://dl.hexchat.net/misc/idpsetup-1.1.2.exe\nidpsetup-1.1.2.exe /VERYSILENT\n  \nREM appveyor DownloadFile https://dl.hexchat.net/gtk-win32/vc14/%arch%/gtk-%platform%.7z\nappveyor DownloadFile https://dl.hexchat.net/gtk/gtk-%platform%-2018-08-29.7z\n7z x gtk-%platform%-*.7z -oC:\\gtk-build\\gtk\n\nappveyor DownloadFile https://dl.hexchat.net/gtk-win32/gendef-20111031.7z\n7z x gendef-20111031.7z -oC:\\gtk-build\n\nappveyor DownloadFile https://dl.hexchat.net/gtk-win32/WinSparkle-20151011.7z\n7z x WinSparkle-20151011.7z -oC:\\gtk-build\\WinSparkle\n\nappveyor DownloadFile https://dl.hexchat.net/misc/perl/perl-5.20.0-%arch%.7z\n7z x perl-5.20.0-%arch%.7z -oC:\\gtk-build\\perl-5.20\\%platform%\n\nmkdir C:\\gtk-build\\python-3.6\nmkdir C:\\gtk-build\\python-2.7\nmklink /d C:\\gtk-build\\python-3.6\\x64 C:\\Python36-x64\nmklink /d C:\\gtk-build\\python-3.6\\Win32 C:\\Python36\nmklink /d C:\\gtk-build\\python-2.7\\x64 C:\\Python27-x64\nmklink /d C:\\gtk-build\\python-2.7\\Win32 C:\\Python27\n\nC:\\Python36-x64\\python.exe -m pip install cffi\nC:\\Python27-x64\\python.exe -m pip install cffi\nC:\\Python36\\python.exe -m pip install cffi\nC:\\Python27\\python.exe -m pip install cffi"
build:
  project: win32\hexchat.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    move ..\hexchat-build\%platform%\HexChat*.exe .\

    move ..\hexchat-build .\
artifacts:
- path: hexchat-build
- path: HexChat*.exe
  name: installer
```

The massive `cmd` isn't very nice though.
